name: Test Backend
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  testing:
    name: Testing Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-md pytest-emoji

      - name: Run tests
        uses: pavelzw/pytest-action@v2
        with:
          emoji: true
          verbose: true
          job-summary: true
          custom-arguments: '--ignore=backend/tests/BDD'
          report-title: 'Backend Test Report'
